# Generated by Django 5.0.3 on 2024-06-10 02:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoodMusic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersongmoods',
            unique_together={('user', 'song', 'moods')},
        ),
    ]
