# Generated by Django 4.2.13 on 2024-07-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MoodMusic", "0004_nummoodssong"),
    ]

    operations = [
        migrations.AddField(
            model_name="nummoodssong",
            name="rateLimit",
            field=models.IntegerField(default=0),
        ),
    ]
